### ISSUE TITLE
DTD is not loaded by config.cson

### ISSUE THREAD

**Issue by stefan-jung** [aerhard/linter-autocomplete-jing#46] opened 2017-04-30 07:43 UTC
I have the following entry in the `config.cson`:

```cson
{
  priority: 2
  test:
    publicId: "-//OASIS//DTD DITA Topic//EN"
    outcome:
      schemaProps: [
        {
           path: "/home/stefan/workspace/DITA/dita-ot/plugins/org.oasis-open.dita.v1_3/dtd/technicalContent/dtd/topic.dtd"
           xmlCatalog: "/home/stefan/workspace/DITA/dita-ot/plugins/org.oasis-open.dita.v1_3/dtd/catalog.xml"
        }
      ]
}
```

I try to validate a standard DITA-XML Topic (DTD):

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA Topic//EN" "topic.dtd">
<topic id="topic">
    <title></title>
    <body>
        <p></p>
    </body>
</topic>
```

I get the validation message:

```
Validation failed: no DTD found ! (DTD)	3:18
Warning	Jing	Could not process schema or catalog: file not found: /home/stefan/Schreibtisch/topic.dtd (Datei oder Verzeichnis nicht gefunden)
```

The validator tries to load the DTD from the same directory, where the DITA-XML file is saved, but it should use the DTD defined in `config.cson`. How can I fix this?

**Comment by aerhard** [comment] 2017-05-14 11:36
Hi Stefan, sorry for the late reply. I think the problem is in `config.cson`: the `xmlCatalog` property needs to be a child of `outcome`. When you move it there, the rules specified in the catalogue file should apply to any document with the PUBLIC ID `-//OASIS//DTD DITA Topic//EN` (unless other matching rules are stronger than this one). When the catalogue contains a rule like this: 

```
<public 
   publicId="-//OASIS//DTD DITA Topic//EN" 
   uri="/home/stefan/workspace/DITA/dita-ot/plugins/org.oasis-open.dita.v1_3/dtd/technicalContent/dtd/topic.dtd"/>
```

you should already be set and get the correct DTD for validation. In this case, you can remove the `schemaProps` specified in `config.cson`.

**Comment by aerhard** [comment] 2017-05-14 11:41
(in case you want to set the schema path in `config.cson`, add `lang: 'dtd'` as a sibling property of `path`)

**Comment by aerhard** [comment] 2017-08-02 03:45
Closing -- please re-open when you've got further issues / questions

**Closed as completed by aerhard** 2017-08-02 03:45 UTC
